# Generated by Django 4.2.6 on 2026-03-26 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Tramites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('total_documentos', models.IntegerField(default=0)),
                ('residente_permanente', models.IntegerField(default=0)),
                ('residente_temporal', models.IntegerField(default=0)),
                ('residente_temp_estudio', models.IntegerField(default=0)),
                ('visitante_humanitario', models.IntegerField(default=0)),
                ('visitante_adopcion', models.IntegerField(default=0)),
                ('visitante_regional', models.IntegerField(default=0)),
                ('visitante_trabajador', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.estado')),
            ],
            options={
                'verbose_name': 'Trámite',
                'verbose_name_plural': 'Trámites',
                'unique_together': {('fecha', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='Retornados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('retornados_total', models.IntegerField(default=0)),
                ('deportado', models.IntegerField(default=0)),
                ('retornado', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.estado')),
            ],
            options={
                'verbose_name': 'Retornado',
                'verbose_name_plural': 'Retornados',
                'unique_together': {('fecha', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='Repatriados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('mex_rep', models.IntegerField(default=0, verbose_name='Mexicanos Repatriados')),
                ('adultos', models.IntegerField(default=0)),
                ('menores', models.IntegerField(default=0)),
                ('nna_solo', models.IntegerField(default=0, verbose_name='NNA No Acompañados')),
                ('nna_acom', models.IntegerField(default=0, verbose_name='NNA Acompañados')),
                ('terrestres', models.IntegerField(default=0)),
                ('vuelos', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.estado')),
            ],
            options={
                'verbose_name': 'Repatriado',
                'verbose_name_plural': 'Repatriados',
                'unique_together': {('fecha', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='Recibidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('ext_rec', models.IntegerField(default=0, verbose_name='Extranjeros Recibidos')),
                ('adultos', models.IntegerField(default=0)),
                ('menores', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.estado')),
            ],
            options={
                'verbose_name': 'Recibido',
                'verbose_name_plural': 'Recibidos',
                'unique_together': {('fecha', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('ingresos_total', models.IntegerField(default=0)),
                ('aereos', models.IntegerField(default=0)),
                ('maritimos', models.IntegerField(default=0)),
                ('terrestres', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.estado')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'unique_together': {('fecha', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='Inadmitidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('inadmitidos_total', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.estado')),
            ],
            options={
                'verbose_name': 'Inadmitido',
                'verbose_name_plural': 'Inadmitidos',
                'unique_together': {('fecha', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='ExtRescatados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('rescatados', models.IntegerField(default=0)),
                ('una_vez', models.IntegerField(default=0)),
                ('reincidente', models.IntegerField(default=0)),
                ('estacion', models.IntegerField(default=0)),
                ('dif', models.IntegerField(default=0)),
                ('conduccion', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.estado')),
            ],
            options={
                'verbose_name': 'Extranjero Rescatado',
                'verbose_name_plural': 'Extranjeros Rescatados',
                'unique_together': {('fecha', 'estado')},
            },
        ),
    ]
