# Generated by Django 4.2.6 on 2026-03-31 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Nacionalidad',
                'verbose_name_plural': 'Nacionalidades',
            },
        ),
        migrations.AlterUniqueTogether(
            name='extrescatados',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='inadmitidos',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ingresos',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='recibidos',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='repatriados',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='retornados',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tramites',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='extrescatados',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapa.nacionalidad'),
        ),
        migrations.AddField(
            model_name='inadmitidos',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapa.nacionalidad'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapa.nacionalidad'),
        ),
        migrations.AddField(
            model_name='recibidos',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapa.nacionalidad'),
        ),
        migrations.AddField(
            model_name='repatriados',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapa.nacionalidad'),
        ),
        migrations.AddField(
            model_name='retornados',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapa.nacionalidad'),
        ),
        migrations.AddField(
            model_name='tramites',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapa.nacionalidad'),
        ),
        migrations.AlterUniqueTogether(
            name='extrescatados',
            unique_together={('fecha', 'estado', 'nacionalidad')},
        ),
        migrations.AlterUniqueTogether(
            name='inadmitidos',
            unique_together={('fecha', 'estado', 'nacionalidad')},
        ),
        migrations.AlterUniqueTogether(
            name='ingresos',
            unique_together={('fecha', 'estado', 'nacionalidad')},
        ),
        migrations.AlterUniqueTogether(
            name='recibidos',
            unique_together={('fecha', 'estado', 'nacionalidad')},
        ),
        migrations.AlterUniqueTogether(
            name='repatriados',
            unique_together={('fecha', 'estado', 'nacionalidad')},
        ),
        migrations.AlterUniqueTogether(
            name='retornados',
            unique_together={('fecha', 'estado', 'nacionalidad')},
        ),
        migrations.AlterUniqueTogether(
            name='tramites',
            unique_together={('fecha', 'estado', 'nacionalidad')},
        ),
    ]
