# Generated by Django 4.2.6 on 2026-04-14 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0002_nacionalidad_alter_extrescatados_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntosInternacionEstacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('AEREO', 'AEREO'), ('MARITIMO', 'MARITIMO'), ('TERRESTRE', 'TERRESTRE'), ('ESTACION', 'ESTACION')], max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.estado')),
            ],
            options={
                'verbose_name': 'Punto de Internacion',
                'verbose_name_plural': 'Puntos de Internacion',
            },
        ),
        migrations.CreateModel(
            name='CatalogoOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=100, unique=True)),
                ('domicilio', models.CharField(max_length=300)),
                ('correo', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.estado')),
            ],
            options={
                'verbose_name': 'Catalogo OR',
                'verbose_name_plural': 'Catalogo ORs',
            },
        ),
    ]
