# Generated by Django 4.2.6 on 2026-04-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0003_puntosinternacionestacion_catalogoor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntosinternacionestacion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='puntosinternacionestacion',
            unique_together={('nombre', 'tipo')},
        ),
    ]
