# Generated by Django 4.2.6 on 2026-04-15 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0004_alter_puntosinternacionestacion_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuentros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('agencia', models.CharField(db_index=True, max_length=100)),
                ('ciudadEU', models.CharField(db_index=True, max_length=100)),
                ('estadoEU', models.CharField(db_index=True, max_length=100)),
                ('encuentros_total', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.estado')),
                ('nacionalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapa.nacionalidad')),
            ],
            options={
                'verbose_name': 'Encuentro',
                'verbose_name_plural': 'Encuentros',
                'unique_together': {('fecha', 'agencia', 'ciudadEU', 'estadoEU', 'estado', 'nacionalidad')},
            },
        ),
    ]
