# Generated by Django 4.2.6 on 2026-04-17 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0005_encuentros'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo PRH',
                'verbose_name_plural': 'Tipos de PRHs',
            },
        ),
        migrations.CreateModel(
            name='PRHs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=False)),
                ('coordenadasTexto', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.estado')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.tipoprh')),
            ],
            options={
                'verbose_name': 'Punto de Rescate',
                'verbose_name_plural': 'Puntos de Rescates',
            },
        ),
    ]
