# Generated by Django 4.2.6 on 2026-05-13 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0006_tipoprh_prhs'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Grado Académico',
                'verbose_name_plural': 'Grados Académicos',
            },
        ),
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='titulares')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Otro')], max_length=1)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('nivel', models.CharField(max_length=20)),
                ('codigo_plaza', models.CharField(max_length=20, unique=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.estado')),
                ('nacionalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapa.nacionalidad')),
            ],
            options={
                'verbose_name': 'Titular',
                'verbose_name_plural': 'Titulares',
            },
        ),
        migrations.CreateModel(
            name='TrayectoriaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('actual', models.BooleanField(default=False)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trayectoria', to='mapa.titular')),
            ],
            options={
                'verbose_name': 'Trayectoria Laboral',
                'verbose_name_plural': 'Trayectorias Laborales',
            },
        ),
        migrations.CreateModel(
            name='TelefonoTitular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PERSONAL', 'Personal'), ('OFICINA', 'Oficina'), ('EMERGENCIA', 'Emergencia'), ('OTRO', 'Otro')], max_length=20)),
                ('numero', models.CharField(max_length=20)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='mapa.titular')),
            ],
            options={
                'verbose_name': 'Teléfono de contacto',
                'verbose_name_plural': 'Teléfonos de contacto',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencia_externa', to='mapa.titular')),
            ],
            options={
                'verbose_name': 'Experiencia Profesional',
                'verbose_name_plural': 'Experiencias Profesionales',
            },
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=150)),
                ('institucion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_conclusion', models.DateField(blank=True, null=True)),
                ('documento_estudio', models.FileField(blank=True, null=True, upload_to='estudios')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapa.gradoacademico')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='mapa.titular')),
            ],
            options={
                'verbose_name': 'Estudio',
                'verbose_name_plural': 'Estudios',
            },
        ),
        migrations.CreateModel(
            name='CorreoTitular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PERSONAL', 'Personal'), ('INSTITUCIONAL', 'Institucional'), ('OTRO', 'Otro')], max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correos', to='mapa.titular')),
            ],
            options={
                'verbose_name': 'Correo electrónico',
                'verbose_name_plural': 'Correos electrónicos',
            },
        ),
    ]
