# Generated by Django 4.2.6 on 2026-05-13 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0007_gradoacademico_titular_trayectorialaboral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNombramiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Nombramiento',
                'verbose_name_plural': 'Tipos de Nombramientos',
            },
        ),
        migrations.AlterField(
            model_name='telefonotitular',
            name='tipo',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('OFICINA', 'Oficina'), ('ASISTENTE', 'Asistente'), ('EMERGENCIA', 'Emergencia'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AddField(
            model_name='titular',
            name='tipo_nombramiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapa.tiponombramiento'),
        ),
    ]
