# Generated by Django 4.2.6 on 2026-05-18 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0008_tiponombramiento_alter_telefonotitular_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProcendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Procedencia',
                'verbose_name_plural': 'Procedencia',
            },
        ),
        migrations.AddField(
            model_name='titular',
            name='procedencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapa.tipoprocendencia'),
        ),
    ]
