# Generated by Django 4.2.6 on 2026-05-19 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0009_tipoprocendencia_titular_procedencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comodato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Comodato',
                'verbose_name_plural': 'Comodatos',
            },
        ),
        migrations.CreateModel(
            name='FiguraOcupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Figura de Ocupación',
                'verbose_name_plural': 'Figuras de Ocupación',
            },
        ),
        migrations.CreateModel(
            name='SituacionActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Situación Actual',
                'verbose_name_plural': 'Situaciones Actuales',
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Actividad',
                'verbose_name_plural': 'Tipos de Actividades',
            },
        ),
        migrations.CreateModel(
            name='TipoInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Inmueble',
                'verbose_name_plural': 'Tipos de Inmuebles',
            },
        ),
        migrations.AlterField(
            model_name='titular',
            name='codigo_plaza',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_inmueble', models.CharField(max_length=200)),
                ('calle', models.CharField(max_length=200)),
                ('numero_exterior', models.CharField(max_length=10)),
                ('numero_interior', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=200)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('superficie_total', models.FloatField()),
                ('superficie_construida', models.FloatField()),
                ('superficie_utilizada', models.FloatField()),
                ('numero_de_niveles', models.IntegerField()),
                ('anio_construccion', models.DateField(blank=True, null=True)),
                ('fecha_ocupacion', models.DateField(blank=True, null=True)),
                ('monto_renta', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vigencia_pipc', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('comodato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapa.comodato')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.estado')),
                ('figura_ocupacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapa.figuraocupacion')),
                ('situacion_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapa.situacionactual')),
                ('tipo_actividad', models.ManyToManyField(blank=True, to='mapa.tipoactividad')),
                ('tipo_inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapa.tipoinmueble')),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
            },
        ),
    ]
