# Generated by Django 4.2.6 on 2026-05-20 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0010_comodato_figuraocupacion_situacionactual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Oficina',
                'verbose_name_plural': 'Tipos de Oficinas',
            },
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='observaciones',
        ),
        migrations.CreateModel(
            name='HistoricoComentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='mapa.inmueble')),
            ],
            options={
                'verbose_name': 'Historial de Comentario',
                'verbose_name_plural': 'Historial de Comentarios',
            },
        ),
        migrations.AddField(
            model_name='inmueble',
            name='tipo_oficina',
            field=models.ManyToManyField(blank=True, to='mapa.tipooficina'),
        ),
    ]
