# Generated by Django 4.2.6 on 2026-05-25 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0011_tipooficina_remove_inmueble_observaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaIPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inm_pipc', models.BooleanField(default=False)),
                ('fecha_inm', models.DateField(blank=True, null=True)),
                ('comodante_pipc', models.BooleanField(default=False)),
                ('fecha_comodante', models.DateField(blank=True, null=True)),
                ('plan_emergencia', models.BooleanField(default=False)),
                ('fecha_inicio_plan', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Programa IPC',
                'verbose_name_plural': 'Programas IPC',
            },
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='vigencia_pipc',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='programa_ipc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapa.programaipc'),
        ),
    ]
