# Generated by Django 4.2.6 on 2026-05-25 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0012_programaipc_remove_inmueble_vigencia_pipc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='programa_ipc',
        ),
        migrations.AddField(
            model_name='programaipc',
            name='inmueble',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pipc', to='mapa.inmueble'),
            preserve_default=False,
        ),
    ]
