# Generated by Django 4.2.6 on 2026-05-26 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0013_remove_inmueble_programa_ipc_programaipc_inmueble'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalINM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.BooleanField(default=True)),
                ('tipo_plaza', models.CharField(choices=[('CONFIANZA', 'CONFIANZA'), ('BASE', 'BASE')], max_length=15)),
                ('codigo_plaza', models.CharField(max_length=20)),
                ('nivel', models.CharField(max_length=4)),
                ('num_empleado', models.CharField(blank=True, max_length=8, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_movimiento', models.BooleanField(blank=True, default=True, null=True)),
                ('fecha_ingreso_inm', models.DateField(blank=True, null=True)),
                ('fecha_ingreso_plza', models.DateField(blank=True, null=True)),
                ('vig_inicio_mov', models.DateField(blank=True, null=True)),
                ('vig_termino_mov', models.DateField(blank=True, null=True)),
                ('puesto_especifico', models.CharField(max_length=200)),
                ('sueldo_bruto', models.FloatField(blank=True, null=True)),
                ('sueldo_neto', models.FloatField(blank=True, null=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapa.tipoactividad')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.estado')),
            ],
            options={
                'verbose_name': 'Personal INM',
                'verbose_name_plural': 'Personal INM',
            },
        ),
    ]
