# Generated by Django 4.2.6 on 2026-05-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0014_personalinm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinm',
            old_name='fecha_ingreso_plza',
            new_name='fecha_ingreso_plaza',
        ),
        migrations.AlterField(
            model_name='personalinm',
            name='estatus',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterUniqueTogether(
            name='personalinm',
            unique_together={('codigo_plaza',)},
        ),
    ]
