# Generated by Django 4.2.6 on 2026-05-28 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0015_rename_fecha_ingreso_plza_personalinm_fecha_ingreso_plaza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinm',
            name='jefe_oficina',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='personalinm',
            name='lugar_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inmuebleAsignado', to='mapa.inmueble'),
        ),
        migrations.AlterField(
            model_name='personalinm',
            name='estatus',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.CreateModel(
            name='OrganigramaF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='Organigramas')),
                ('vigencia', models.DateField(blank=True, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.estado')),
            ],
            options={
                'verbose_name': 'Organigrama',
                'verbose_name_plural': 'Organigramas',
                'unique_together': {('estado',)},
            },
        ),
    ]
