# Generated by Django 4.2.6 on 2026-06-05 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0016_personalinm_jefe_oficina_personalinm_lugar_asignado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Estatus P',
                'verbose_name_plural': 'Estatus P',
            },
        ),
        migrations.CreateModel(
            name='TipoPlaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plazaT', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo Plaza',
                'verbose_name_plural': 'Tipos Plazas',
            },
        ),
        migrations.AddField(
            model_name='personalinm',
            name='curp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personalinm',
            name='estatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapa.estatuspersonal'),
        ),
        migrations.AlterField(
            model_name='personalinm',
            name='tipo_plaza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapa.tipoplaza'),
        ),
    ]
