# Generated by Django 4.2.6 on 2026-06-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0017_estatuspersonal_tipoplaza_personalinm_curp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinm',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinm',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Otro')], max_length=1, null=True),
        ),
    ]
