# Generated by Django 4.2.6 on 2026-06-17 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0019_personalinm_actividad_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad', to='mapa.tipoactividad')),
            ],
            options={
                'verbose_name': 'Tipo de Dependencia',
                'verbose_name_plural': 'Tipos de Dependencias',
            },
        ),
        migrations.AlterField(
            model_name='personalinm',
            name='actividad',
            field=models.ManyToManyField(blank=True, to='mapa.tipodependencia'),
        ),
    ]
