# Generated by Django 4.2.6 on 2026-06-22 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0020_tipodependencia_alter_personalinm_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoMotivoBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotosVeh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frente', models.FileField(blank=True, null=True, upload_to='fotosVeh')),
                ('lateral', models.FileField(blank=True, null=True, upload_to='fotosVeh')),
                ('trasera', models.FileField(blank=True, null=True, upload_to='fotosVeh')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAsignacionVeh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVeh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_veh', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehiculosOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('anio', models.DateField(blank=True, null=True)),
                ('placa', models.CharField(max_length=20)),
                ('no_motor', models.CharField(max_length=20)),
                ('tarjeta_asig', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_disp_comb', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.tipoasignacionveh')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.estado')),
                ('fotografias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapa.fotosveh')),
                ('inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapa.inmueble')),
                ('tipoVeh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapa.tipoveh')),
            ],
        ),
        migrations.CreateModel(
            name='Siniestros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('folio', models.CharField(blank=True, max_length=200, null=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.vehiculosor')),
            ],
        ),
        migrations.CreateModel(
            name='PrestadoDe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(blank=True, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.estado')),
                ('inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapa.inmueble')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.vehiculosor')),
            ],
        ),
        migrations.CreateModel(
            name='MotivoBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=200, null=True)),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapa.catalogomotivobaja')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.vehiculosor')),
            ],
        ),
        migrations.CreateModel(
            name='Kilometraje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('KM', 'kilometro'), ('MI', 'Milla')], max_length=20)),
                ('odometro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='fotosVeh')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.vehiculosor')),
            ],
        ),
        migrations.CreateModel(
            name='CombustibleExt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.vehiculosor')),
            ],
        ),
        migrations.CreateModel(
            name='Capufe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.vehiculosor')),
            ],
        ),
    ]
