# Generated by Django 4.2.6 on 2026-06-22 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0021_catalogomotivobaja_fotosveh_tipoasignacionveh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituacionVeh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='vehiculosor',
            name='situacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapa.situacionveh'),
        ),
    ]
