# Generated by Django 4.2.6 on 2026-08-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0022_situacionveh_vehiculosor_situacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculosor',
            name='balizado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='vehiculosor',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
