# Generated by Django 4.2.6 on 2026-09-01 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapa', '0022_situacionveh_vehiculosor_situacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMexExtPunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('estado', models.CharField(choices=[('BAJA CALIFORNIA', 'Baja California'), ('SONORA', 'Sonora'), ('CHIHUAHUA', 'Chihuahua'), ('COAHUILA', 'Coahuila'), ('TAMAULIPAS', 'Tamaulipas')], db_index=True, max_length=50)),
                ('punto', models.CharField(choices=[('TIJUANA', 'Tijuana'), ('MEXICALI', 'Mexicali'), ('SAN LUIS RÍO COLORADO', 'San Luis Río Colorado'), ('NOGALES', 'Nogales'), ('AGUA PRIETA', 'Agua Prieta'), ('CIUDAD JUÁREZ', 'Ciudad Juárez'), ('OJINAGA', 'Ojinaga'), ('CIUDAD ACUÑA', 'Ciudad Acuña'), ('PIEDRAS NEGRAS', 'Piedras Negras'), ('NUEVO LAREDO', 'Nuevo Laredo'), ('REYNOSA', 'Reynosa'), ('MATAMOROS', 'Matamoros')], max_length=50)),
                ('categoria', models.CharField(choices=[('MEX', 'Mexicano'), ('EXT', 'Extranjero')], max_length=3)),
                ('hombres', models.IntegerField(default=0)),
                ('mujeres', models.IntegerField(default=0)),
                ('ninos', models.IntegerField(default=0)),
                ('ninas', models.IntegerField(default=0)),
                ('nacionalidad', models.ForeignKey(blank=True, help_text='Solo aplica si categoria=Extranjero', null=True, on_delete=django.db.models.deletion.CASCADE, to='mapa.nacionalidad')),
            ],
            options={
                'verbose_name': 'Registro Mex/Ext por Punto',
                'verbose_name_plural': 'Registros Mex/Ext por Punto',
            },
        ),
        migrations.AddConstraint(
            model_name='registromexextpunto',
            constraint=models.UniqueConstraint(condition=models.Q(('categoria', 'MEX')), fields=('fecha', 'punto', 'categoria'), name='unico_mex_por_punto_fecha'),
        ),
        migrations.AddConstraint(
            model_name='registromexextpunto',
            constraint=models.UniqueConstraint(condition=models.Q(('categoria', 'EXT')), fields=('fecha', 'punto', 'categoria', 'nacionalidad'), name='unico_ext_por_punto_fecha_nacionalidad'),
        ),
    ]
