# Generated by Django manual migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_msgupdate_info_usuario_str_pass_usuario_tipo_disp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidacionServidor',
            fields=[
                ('idValidacion', models.AutoField(primary_key=True, serialize=False)),
                ('servidor_url', models.URLField(help_text='URL base del servidor a consultar', max_length=255)),
                ('servidor_backup_url', models.URLField(blank=True, help_text='URL del servidor de respaldo', max_length=255, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el servidor está activo')),
                ('version_minima_app', models.CharField(default='1.0.0', help_text='Versión mínima requerida de la app móvil', max_length=20)),
                ('mensaje', models.CharField(blank=True, help_text='Mensaje informativo para la app', max_length=500, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
