from django.urls import path, include
from mapa import views

urlpatterns = [
    path('informacion', views.mapa_informacion, name="mostrar_mapa"),
    path('mapa-interactivo', views.mapa_interactivo, name="mostrar_mapa_int"),
    path('mapa-ejemplo', views.mapa_ejemplo, name="mapa_ejemplo"),
    path('carga-datos', views.carga_datos, name="carga_datos"),
    path('carga-nacionalidades', views.carga_nacionalidades, name="carga_nacionalidades"),
    path('carga-oficinas', views.carga_oficinas, name="carga_oficinas"),
    
    path('titulares', views.titulares_list, name="titulares_list"),
    path('carga-datos-batch', views.carga_datos_batch, name="carga_datos_batch"),
    path('api/periodo-custom', views.api_periodo_custom, name="api_periodo_custom"),
    path('api/nacionalidad-ranking', views.api_nacionalidad_ranking, name="api_nacionalidad_ranking"),
    path('api/reporte-nacionalidades', views.api_reporte_nacionalidades, name="api_reporte_nacionalidades"),
    path('reportes', views.reportes, name="reportes"),
    # @FADAR
    path('reportes/mexicanos-extranjeros', views.reporte_mex_extranjeros, name="reporte_mex_extranjeros"),
    path('reportes/mexicanos-extranjeros/pdf', views.reporte_mex_extranjeros_pdf, name="reporte_mex_extranjeros_pdf"),
    path('reportes/mexicanos-extranjeros/excel', views.reporte_mex_extranjeros_excel, name="reporte_mex_extranjeros_excel"),
    path('guardar-titular', views.guardar_titular, name="guardar_titular"),
    path('eliminar-titular/<int:titular_id>', views.eliminar_titular, name="eliminar_titular"),
    path('api/get-titular/<int:titular_id>', views.api_get_titular, name="api_get_titular"),
    path('personal', views.personal_list, name="personal_list"),
    path('carga-rapida-personal', views.carga_rapida_personal, name="carga_rapida_personal"),
    path('guardar-personal', views.guardar_personal, name="guardar_personal"),
    path('eliminar-personal/<int:personal_id>', views.eliminar_personal, name="eliminar_personal"),
    path('api/get-personal/<int:personal_id>', views.api_get_personal, name="api_get_personal"),

    path('inmuebles', views.inmuebles_list, name="inmuebles_list"),
    path('guardar-inmueble', views.guardar_inmueble, name="guardar_inmueble"),
    path('eliminar-inmueble/<int:inmueble_id>', views.eliminar_inmueble, name="eliminar_inmueble"),
    path('api/get-inmueble/<int:inmueble_id>', views.api_get_inmueble, name="api_get_inmueble"),
    path('api/guardar-comodato', views.api_guardar_comodato, name="api_guardar_comodato"),
    path('api/get-inmueble-detalle/<int:inmueble_id>', views.api_get_inmueble_detalle, name="api_get_inmueble_detalle"),
    path('api/get-estado-detalle/<int:estado_id>', views.api_get_estado_detalle, name="api_get_estado_detalle"),
    path('api/get-personal-stats/<int:estado_id>', views.api_get_personal_stats, name="api_get_personal_stats"),
    
    path('organigramas', views.organigramas_list, name="organigramas_list"),
    path('guardar-organigrama', views.guardar_organigrama, name="guardar_organigrama"),
    path('eliminar-organigrama/<int:org_id>', views.eliminar_organigrama, name="eliminar_organigrama"),
    path('api/get-organigrama/<int:estado_id>', views.api_get_organigrama, name="api_get_organigrama"),
    
    path('vehiculos', views.vehiculos_list, name="vehiculos_list"),
    path('guardar-vehiculo', views.guardar_vehiculo, name="guardar_vehiculo"),
    path('eliminar-vehiculo/<int:vehiculo_id>', views.eliminar_vehiculo, name="eliminar_vehiculo"),
    path('api/get-vehiculo/<int:vehiculo_id>', views.api_get_vehiculo, name="api_get_vehiculo"),
    
    path('api/get-vehiculo-historial/<int:vehiculo_id>', views.api_get_vehiculo_historial, name="api_get_vehiculo_historial"),
    path('guardar-kilometraje', views.guardar_kilometraje, name="guardar_kilometraje"),
    path('guardar-prestado', views.guardar_prestado, name="guardar_prestado"),
    path('guardar-siniestro', views.guardar_siniestro, name="guardar_siniestro"),
    path('guardar-capufe', views.guardar_capufe, name="guardar_capufe"),
    path('guardar-combustible', views.guardar_combustible, name="guardar_combustible"),
    
    path('prhs', views.prhs_list, name="prhs_list"),
    path('guardar-prh', views.guardar_prh, name="guardar_prh"),
    path('eliminar-prh/<int:prh_id>', views.eliminar_prh, name="eliminar_prh"),
    path('api/get-prh/<int:prh_id>', views.api_get_prh, name="api_get_prh"),
    
    path('puntos-internacion', views.puntos_internacion_list, name="puntos_internacion_list"),
    path('guardar-punto-internacion', views.guardar_punto_internacion, name="guardar_punto_internacion"),
    path('eliminar-punto-internacion/<int:punto_id>', views.eliminar_punto_internacion, name="eliminar_punto_internacion"),
    path('api/get-punto-internacion/<int:punto_id>', views.api_get_punto_internacion, name="api_get_punto_internacion"),

    path('rescates', views.rescates_dashboard, name="rescates_dashboard"),
    path('rescates/regiones', views.rescates_regiones, name="rescates_regiones"),
    path('rescates/reportes/cuadro', views.rescates_reporte_cuadro, name="rescates_reporte_cuadro"),
    path('rescates/reportes/cuadro/pdf', views.rescates_reporte_cuadro_pdf, name="rescates_reporte_cuadro_pdf"),
    path('rescates/reportes/cuadro/excel', views.rescates_reporte_cuadro_excel, name="rescates_reporte_cuadro_excel"),
    path('rescates/reportes/informe', views.rescates_reporte_informe, name="rescates_reporte_informe"),
    path('rescates/reportes/informe/pdf', views.rescates_reporte_informe_pdf, name="rescates_reporte_informe_pdf"),
    path('rescates/reportes/informe/excel', views.rescates_reporte_informe_excel, name="rescates_reporte_informe_excel"),
    path('rescates/reportes/regiones', views.rescates_reporte_regiones, name="rescates_reporte_regiones"),
    path('rescates/reportes/regiones/pdf', views.rescates_reporte_regiones_pdf, name="rescates_reporte_regiones_pdf"),
    path('rescates/reportes/regiones/excel', views.rescates_reporte_regiones_excel, name="rescates_reporte_regiones_excel"),
    path('rescates/reportes/ceco2', views.rescates_reporte_ceco2, name="rescates_reporte_ceco2"),
    path('rescates/reportes/ceco2/pdf', views.rescates_reporte_ceco2_pdf, name="rescates_reporte_ceco2_pdf"),
    path('rescates/reportes/ceco2/excel', views.rescates_reporte_ceco2_excel, name="rescates_reporte_ceco2_excel"),
    path('rescates/reportes/ceco-v1', views.rescates_reporte_cecov1, name="rescates_reporte_cecov1"),
    path('rescates/reportes/ceco-v1/pdf', views.rescates_reporte_cecov1_pdf, name="rescates_reporte_cecov1_pdf"),
    path('rescates/reportes/ceco-v1/excel', views.rescates_reporte_cecov1_excel, name="rescates_reporte_cecov1_excel"),
    path('rescates/reportes/ceco-v2', views.rescates_reporte_cecov2, name="rescates_reporte_cecov2"),
    path('rescates/reportes/ceco-v2/pdf', views.rescates_reporte_cecov2_pdf, name="rescates_reporte_cecov2_pdf"),
    path('rescates/reportes/ceco-v2/excel', views.rescates_reporte_cecov2_excel, name="rescates_reporte_cecov2_excel"),
    path('rescates/reportes/personalizado', views.rescates_reporte_personalizado, name="rescates_reporte_personalizado"),
    path('rescates/reportes/personalizado/pdf', views.rescates_reporte_personalizado_pdf, name="rescates_reporte_personalizado_pdf"),
    path('rescates/reportes/personalizado/excel', views.rescates_reporte_personalizado_excel, name="rescates_reporte_personalizado_excel"),
]